name: tn_discord
description: A powerful Dart library for interacting with the Discord API.
version: 1.1.0
repository: https://github.com/ThunderNetworkRaD/discord.dart


environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  events_emitter: ^0.5.2
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
